### PR TITLE
Fixed simple/ link.

### PR DESCRIPTION
**Pull request by kyso**
Weird Github is weird?

### CODE REVIEW

**Comment by joeyespo** [comment]
Thanks, Kyso!

Here's hoping GitHub fixes their relative URLs in Readme previews soon.
Once they do, this should be reverted since it breaks relative URLs outside of GitHub.

**Comment by joeyespo** [comment]
Relevant issue: https://github.com/github/markup/issues/101

**Comment by FichteFoll** [comment]
I doubt you'll remember this commit whenever that finally happens.

Btw, this only works when accessing the link from [here](https://github.com/Kyso/gitpress/blob/master/examples/README.md), not from [here](https://github.com/Kyso/gitpress/tree/master/examples). A static link to `https://github.com/Kyso/gitpress/tree/master/examples/simple` might be required.

Edit: Now it's actually the opposite since you merge-merged it to the master branch.

**Comment by joeyespo** [comment]
@FichteFoll Yeah, it's a little bit of a pain relative URLs don't work right. It's even worse that relative images are broken in the same way.

It's leading me to use less linking on blog repositories I also push to GitHub so it doesn't appear "broken" even though the URLs are perfectly valid when hosted anywhere else.

> I doubt you'll remember this commit whenever that finally happens.

Created issue #5 to keep track of this =)

**Pull request merged**
